ROM/urls.py
from django.views.generic import RedirectView
from common.views import LoginUsuario
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from common.views import InitialView, user_logout, RegisterView

urlpatterns = [
    path('credicol-register/', RegisterView.as_view(), name='register'),
    path('admin/', admin.site.urls),
    path('dashboard/', InitialView.as_view(), name='initial_view'),
    path('', RedirectView.as_view(url='/login/')),
    path('login/', LoginUsuario.as_view(), name='login'),
    path('logout/<str:origin>', user_logout, name='user_logout'),
    path('transacciones/', include('transacciones.urls')),
    path('common/', include('common.urls')),
    path('clientes/', include('clientes.urls')),
    path('productos/', include('productos.urls')),
    path('gastos/', include('gastos.urls')),
    path('stv/', include('stv.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stv/urls.py
from django.urls import path
from . import views
from . import api_views

app_name = 'stv'

urlpatterns = [
    path('', views.InitialStvView.as_view(), name='initial_stv'),
    path('login', views.LoginStvUser.as_view(), name='stv_login'),
    path('reports', views.ListReportsView.as_view(), name='report_list'),
    path(
        'api/stv-reportes/',
        api_views.ListarReportesAPIView.as_view(),
        name='listar_reportes_api'
    ),
    path('add-new-report', views.AddReportView.as_view(), name='add_new_report'),
    path('download-report/<int:id>', views.download_report, name='download_report'),
    path('empleados', views.ListEmpleadosView.as_view(), name='empleados_list'),
    path(
        'api/stv-empleados/',
        api_views.ListarEmpleadosAPIView.as_view(),
        name='listar_empleados_api'
    ),
    path('add-new-empleado', views.AddEmpleadoView.as_view(), name='add_new_empleado'),
    path('edit-empleado/<int:pk>', views.EditEmpleadoView.as_view(), name='edit_empleado'),
]

stv/models.py
from django.db import models
from django.contrib.auth.models import User


class Reporte(models.Model):
    TIPOS_REPORTE = [
        ('preventivo', 'Preventivo'),
        ('reparacion', 'Reparación'),
        ('correctivo', 'Correctivo'),
        ('inspeccion_norma', 'Inspección Norma'),
        ('otros', 'Otros')
    ]

    archivo = models.FileField(upload_to='reportes/')
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    cliente = models.CharField(max_length=255)
    ciudad = models.CharField(max_length=255)
    tecnico = models.ForeignKey(User, on_delete=models.CASCADE)
    tipo_reporte = models.CharField(max_length=20, choices=TIPOS_REPORTE, blank=True, null=True)

    def __str__(self):
        return f"Reporte {self.id} - {self.cliente} - {self.fecha_creacion.strftime('%Y-%m-%d %H:%M:%S')} - {self.get_tipo_reporte_display()}"

    class Meta:
        permissions = [
            ("can_see_reports", "Can see reporte"),
            ("can_upload_reports", "Can upload reporte"),
        ]


class Empleado(models.Model):

    CARGO_OPCIONES = [
        ('tecnico', 'Técnico'),
    ]

    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15, blank=True, null=True)
    puesto = models.CharField(max_length=50, choices=CARGO_OPCIONES)
    fecha_creacion = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.nombre} {self.apellido} - {self.puesto}'

    class Meta:
        verbose_name = "Empleado"
        verbose_name_plural = "Empleados"
        ordering = ['apellido', 'nombre']

        permissions = [
            ("can_see_empleados", "Can see empleados")
        ]

stv/forms.py
from django import forms

from . import models as m


class AddNewReport(forms.ModelForm):

    ciudad = forms.CharField(max_length=255, required=True)
    cliente = forms.CharField(max_length=255, required=True)

    class Meta:
        model = m.Reporte
        fields = [
            'ciudad',
            'cliente',
            'tipo_reporte'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.required = True
            field.label = ''

    def save(self, user, commit=True):
        producto = super().save(commit=False)
        producto.tecnico = user

        if commit:
            producto.save()

        return producto


class AddNewEmpleado(forms.ModelForm):

    class Meta:
        model = m.Empleado
        fields = [
            'nombre',
            'apellido',
            'telefono',
            'puesto'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.required = True
            field.label = ''

    def save(self, user, commit=True):
        empleado = super().save(commit=False)
        empleado.user = user

        if commit:
            empleado.save()

        return empleado


class EditEmpleado(forms.ModelForm):

    class Meta:
        model = m.Empleado
        fields = [
            'nombre',
            'apellido',
            'telefono',
            'puesto'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.required = True
            field.label = ''

stv/views.py
import os

from django.conf import settings
from django.views import generic
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django.db import transaction
from django.http.response import JsonResponse
from django.http import FileResponse, Http404
from django.shortcuts import resolve_url
from django.contrib.auth.views import LoginView
from django.contrib.auth import get_user_model
from .models import Reporte, Empleado
from . import forms as f
from . import services as s

User = get_user_model()


class InitialStvView(generic.TemplateView):

    template_name = 'stv/initial.html'
    permission_required = 'stv.can_see_initial_view'


class LoginStvUser(LoginView):
    template_name = 'stv/login_stv.html'
    redirect_authenticated_user = True
    success_url = 'stv:report_list'

    def form_invalid(self, form):

        try:
            self.usuario = User.objects.get(
                username=self.request.POST['username']
            )
        except Exception:
            return super().form_invalid(form)

        return super().form_invalid(form)

    def form_valid(self, form):

        try:
            self.usuario = form.get_user()
        except Exception:
            return super().form_invalid(form)

        return super().form_valid(form)

    def get_success_url(self):
        return resolve_url(self.success_url)


class ListReportsView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.TemplateView
):

    template_name = 'stv/report_list.html'
    permission_required = 'stv.can_see_reports'


class AddReportView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView
):
    model = Reporte
    form_class = f.AddNewReport
    template_name = 'stv/components/form_add_report.html'
    permission_required = 'stv.can_upload_reports'

    def form_valid(self, form):
        cliente = form.instance.cliente.title()
        s.create_new_report(form.instance, self.request)
        form.save(self.request.user)
        return JsonResponse(
            {
                'ok': True, 'product': cliente, 'label': 'creado'
            }
        )


def download_report(request, id):
    with transaction.atomic():
        try:
            report = Reporte.objects.get(id=id)
            file_name = report.archivo.name
            file_path = f'{settings.MEDIA_ROOT}/reportes/{file_name}'

            if not os.path.exists(file_path):
                raise Http404("Archivo no encontrado.")

            response = FileResponse(open(file_path, 'rb'), as_attachment=True, filename=os.path.basename(file_path))
            return response

        except Reporte.DoesNotExist:
            raise Http404("Reporte no encontrado.")


class ListEmpleadosView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.TemplateView
):

    template_name = 'stv/empleados_list.html'
    permission_required = 'stv.can_see_empleados'


class AddEmpleadoView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView
):
    model = Empleado
    form_class = f.AddNewEmpleado
    template_name = 'stv/components/form_add_empleado.html'
    permission_required = 'stv.can_see_empleados'

    def form_valid(self, form):
        nombre = form.instance.nombre.title()
        apellido = form.instance.apellido.title()
        user = s.create_new_empleado_user(nombre, apellido)
        form.save(user)
        return JsonResponse(
            {
                'ok': True, 'product': nombre, 'label': 'creado'
            }
        )


class EditEmpleadoView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView
):
    model = Empleado
    form_class = f.EditEmpleado
    template_name = 'stv/components/form_add_empleado.html'
    permission_required = 'stv.can_see_empleados'

    def form_valid(self, form):
        nombre = form.instance.nombre.title()
        form.save()

        return JsonResponse(
            {
                'ok': True, 'product': nombre, 'label': 'actualizado'
            }
        )

templates/stv/login_stv.html
{% load static%}


{% block css %}

    <style>

        @media only screen and (max-width: 768px) {
            .elemento-ocultable {
                display: none;
            }

            html, body {
                height: 100%;
                margin: 0;
            }

            .container {
                margin-top: calc(50vh - 90%)
            }

        }

        body {
            background: linear-gradient(to bottom, #eae700, #eae700);
        }

        .card::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            border-radius: inherit;
            box-shadow: 0 0 30px 22px rgba(0, 0, 0, 0.5);
            opacity: 0;
            transition: opacity 0.5s ease;
        }
    
        .card:hover::before {
            opacity: 1;
        }   

    </style>

{% endblock css %}



<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/x-icon" href="{% static 'img/stv/logo.png' %}" />

    <title>STV | Iniciar Sesion</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body>

    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">
            

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-body p-0"  style="z-index:999;">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            {% comment %} <div class="col-lg-6 d-none d-lg-block bg-login-image-2"></div> <!--Aca va la vieja imagen dog--> {% endcomment %}
                            <div class="elemento-ocultable col-lg-6 d-none d-lg-block bg-login-image-2 fade-in borde-amarillo" style="border-right: 2px solid #ccc; background-image: url('{% static 'img/stv/login_image.jpg' %}'); background-position: center; background-size: cover;">
                                <!-- Contenido opcional dentro del div -->
                            </div>
                            <div class="col-lg-6">
                                <div class="col-12 d-lg-none border elemento-ocultable" style="background-image: url('{% static 'img/stv/logo.png' %}'); background-position: center; background-size: cover; height:150px;">

                                </div>
                                <div class="p-4">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4"><strong>Inicia sesión</strong></h1>
                                    </div>
                                    <form method="post">
                                        {% csrf_token %}
                                        <div id="div_id_username" class="form-group">
                                            <label for="id_username" class=" requiredField">
                                                Nombre de usuario<span class="asteriskField">*</span>
                                            </label>
                                            <div class="">
                                                <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" class="textinput textInput form-control" required="" id="id_username">
                                            </div>
                                        </div>
                                        <div id="div_id_password" class="form-group">
                                            <label for="id_password" class=" requiredField">
                                                Contraseña<span class="asteriskField">*</span>
                                            </label>
                                            <div class="">
                                                <input type="password" name="password" autofocus="" autocapitalize="none" autocomplete="password" maxlength="150" class="textinput textInput form-control" required="" id="id_password">
                                            </div>
                                        </div>
                                        <br>
                                        <div class="form-group text-center">
                                            <button type="submit" class="btn btn-dark btn-sm px-4" name="button" style="color: #FFFFF; background-color: black;">
                                                Acceder
                                            </button>                                                                                    </div>
                                        {% if form.errors %}
                                        {% for field in form %}
                                            {% for error in field.errors %}
                                                <div class="alert alert-danger">
                                                    {{ error|escape }}
                                                </div>
                                            {% endfor %}
                                        {% endfor %}
                                        {% endif %}

                                        {% include 'components/non_field_errors.html' with form=form %}
                                        <div style="display:none;">
                                            <div class="text-center">
                                                <a class="small" href="#">¿Olvidaste tu contraseña?</a>
                                                <br>
                                                <a class="small" href="{% static 'mw_manual_uso.pdf' %}" target="_blank" data-toggle="tooltip" data-placement="top" title="haz clic para ver el instructivo">Crear Cuenta</a> 
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="elemento-ocultable" id="layoutAuthentication_footer" style="margin-top:19%;">
        <footer class="footer mt-auto footer-dark">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6 small" style="color:black;">Copyright &copy; STV 2024</div>
                    <div class="col-md-6 text-md-right small">
                        <a href="#!" style="color:black;">Privacy Policy</a>
                        &middot;
                        <a href="#!" style="color:black;">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
        

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

templates/stv/stv_base.html
{% load static waffle_tags crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% comment %} <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> {% endcomment %}
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <link rel="icon" type="image/x-icon" href="{% static 'img/stv/logo.png' %}" />
    <script src="{% static 'app_stv/js/app.js' %}"></script>
    <link rel="manifest" href="{% static 'app_stv/manifest.json' %}"/>
    {% block css %}{% endblock css %}

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        {% include "stv/stv_sidebar.html" %}
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                {% include "stv/stv_navbar.html" %}
                {% block content %}
                {% endblock %}
            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; STV 2024</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>

    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-dark" id="exampleModalLabel">Deseas cerrar sesión?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body text-dark">Selecciona "Salir" si deseas cerrar la sesión actual.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                    <a class="btn btn-primary" href="{% url 'user_logout' 'stv' %}">Salir</a>
                </div>
            </div>
        </div>
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js'%}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js'%}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js'%}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js'%}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js'%}"></script>
    <script src="https://unpkg.com/sweetalert2@7.8.2/dist/sweetalert2.all.js"
        integrity="sha384-TXx4nFk9yfqhYyuOr5TSNDLkwYpxvszQRKWzlWSQopwFpZsUPq/z1wQtH61CW6ex" 
        crossorigin="anonymous">
    </script>
    <script>
    
 
    ocultarEnMovil()

    function ocultarEnMovil() {

        if (!window.matchMedia("(max-width: 768px)").matches) {
            $("body").toggleClass("sidebar-toggled");
            $(".sidebar").toggleClass("toggled");
            if ($(".sidebar").hasClass("toggled")) {
                $('.sidebar .collapse').collapse('hide');
            };
        }
    }

    </script>

    {% block js %}
    {% endblock %}

templates/stv/stv_sidebar.html
{% load static waffle_tags crispy_forms_tags %}

{% block css %}
    <style>
        ::-webkit-scrollbar {
            width: 7px;
        }

        ::-webkit-scrollbar-track {
            background-color: #FFFFF;
        }

        ::-webkit-scrollbar-thumb {
            background-color: gray;
            border-radius: 1px;
        }

        @media only screen and (max-width: 768px) {
            .elemento-ocultable {
                display: none;
            }
        }

        .ancho-personalizado {
            width: 600px;
        }

        .nav-link.active {
            background-color: #FFC107; /* Amarillo STV */
            color: black !important;
            border-radius: 10px;
            opacity: 90%;
            margin-left: 5px;
            margin-right: 15px;
        }

        .nav-link.active * {
            color: black;
        }

        /* Sidebar */
        .sidebar {
            background: #000000; /* Negro STV */
            color: #FFC107; /* Amarillo STV */
        }

        .sidebar .nav-link {
            color: #FFC107; /* Amarillo STV */
        }

        .sidebar .nav-link:hover {
            background-color: #FFC107;
            color: #000000;
        }

        .sidebar .sidebar-brand {
            color: #FFC107; /* Amarillo STV */
        }

        .sidebar .sidebar-brand-icon {
            color: #FFC107; /* Amarillo STV */
        }

        .sidebar .sidebar-brand-text {
            color: #FFC107; /* Amarillo STV */
        }

        .sidebar .nav-item .nav-link.active {
            background-color: #FFC107; /* Amarillo STV */
            color: #000000; /* Negro STV */
        }

        .sidebar .nav-item .nav-link.active i {
            color: #000000; /* Negro STV */
        }

        .sidebar-card {
            background-color: #000000; /* Negro STV */
            color: #FFC107; /* Amarillo STV */
        }

        .sidebar-card .btn {
            background-color: #FFC107; /* Amarillo STV */
            color: #000000; /* Negro STV */
        }

        .sidebar-card .btn:hover {
            background-color: #e0a800; /* Amarillo oscuro */
            color: #000000; /* Negro STV */
        }

        /* Modal Styles */
        .modal-content {
            border-radius: 8px;
            {% comment %} background-color: #000000; /* Negro STV */ {% endcomment %}
            color: #FFC107; /* Amarillo STV */
        }

        .modal-header {
            border-bottom: 1px solid #FFC107; /* Amarillo STV */
        }

        .modal-header .close {
            color: #FFC107; /* Amarillo STV */
        }

        .modal-footer .btn-primary {
            background-color: #FFC107; /* Amarillo STV */
            border-color: #FFC107; /* Amarillo STV */
        }

        .modal-footer .btn-primary:hover {
            background-color: #e0a800; /* Amarillo oscuro */
        }
    </style>
{% endblock css %}

<ul class="navbar-nav bg-gradient-dark sidebar toggled sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'initial_view' %}">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-map-marker-alt fa-1x"></i>
        </div>
        <div class="sidebar-brand-text mx-3">{{ request.user.company_profile.name }}</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <li class="nav-item">
        <a class="nav-link" href="{% url 'initial_view' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Inicio</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'stv:empleados_list' %}">
            <i class="fas fa-fw fa-user-alt"></i>
            <span>Empleados</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'stv:report_list' %}">
            <i class="fas fa-fw fa-file-alt"></i>
            <span>Reportes</span>
        </a>
    </li>

    <br>
    <hr class="sidebar-divider d-none d-md-block">

    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

    {% comment %} <div class="sidebar-card d-none d-lg-flex">
        <img class="sidebar-card-illustration mb-2" src="{% static 'img/undraw_rocket.svg' %}" alt="...">
        <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
        <a class="btn btn-success btn-sm" href="{% static 'https://startbootstrap.com/theme/sb-admin-pro' %}">Upgrade to Pro!</a>
    </div> {% endcomment %}

    <form id="delete-form" method="POST">
        {% csrf_token %}
    </form>
    <div id="form-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="form-title"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="form-title"></h5>
                    <button class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="form" method="POST">
                        Cargando...
                    </form>
                </div>
                <div class="modal-footer">
                    <button id="form-button" class="btn btn-primary" type="submit" form="form"></button>
                </div>
            </div>
        </div>
    </div>
</ul>