ROM/urls.py
from django.views.generic import RedirectView
from common.views import LoginUsuario
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from common.views import InitialView, user_logout, RegisterView

urlpatterns = [
    path('credicol-register/', RegisterView.as_view(), name='register'),
    path('admin/', admin.site.urls),
    path('dashboard/', InitialView.as_view(), name='initial_view'),
    path('', RedirectView.as_view(url='/login/')),
    path('login/', LoginUsuario.as_view(), name='login'),
    path('logout/<str:origin>', user_logout, name='user_logout'),
    path('transacciones/', include('transacciones.urls')),
    path('common/', include('common.urls')),
    path('clientes/', include('clientes.urls')),
    path('productos/', include('productos.urls')),
    path('gastos/', include('gastos.urls')),
    path('stv/', include('stv.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientes/urls.py
from django.urls import path

from . import views, api_views

app_name = 'clientes'
urlpatterns = [
    path('', views.ListUsersView.as_view(), name='clientes_list'),
    path(
        'api/clientes/<str:company_id>',
        api_views.ListarClientesAPIView.as_view(),
        name='listar_clientes_api'
    ),
    path(
        'cliente/<int:id>', views.ClienteDetailView.as_view(),
        name='profile'
    ),
    path('add-new', views.AddClienteView.as_view(), name='add_new_cliente'),
    path(
        'editar-cliente/<int:pk>',
        views.ClienteEditView.as_view(),
        name='edit_cliente'
    ),
]

gastos/urls.py
from django.urls import path

from . import api_views
from . import views

app_name = 'gastos'

urlpatterns = [
    path(
        '',
        views.ListAllGastosView.as_view(),
        name='full_gastos_list'
    ),
    path(
        'api/gastos/',
        api_views.ListarAllGastosAPIView.as_view(),
        name='listar_all_gastos_api'
    ),
    path('add-gasto/', views.AddGastoView.as_view(), name='add_gasto'),
    path(
        'edit-gasto/<int:pk>/', views.EditGastoView.as_view(),
        name='edit_gasto'
    ),
]

productos/urls.py
from django.urls import path

from . import views, api_views

app_name = 'productos'
urlpatterns = [
    path('', views.ListProductosView.as_view(), name='productos_list'),
    path(
        'api/productos/<str:producto_id>',
        api_views.ListarProductosAPIView.as_view(),
        name='listar_productos_api'
    ),
    # path('cliente/<int:id>', views.ClienteDetailView.as_view(), name='profile'),
    path('add-new', views.AddProductoView.as_view(), name='add_new_producto'),
    path('editar-producto/<int:pk>', views.EditarProductoView.as_view(), name='editar_producto'),
    path('detalle/<int:pk>', views.DetailProductoView.as_view(), name='detalle_producto'),
    # path('editar-cliente/<int:pk>', views.ClienteEditView.as_view(), name='edit_cliente'),
]

transacciones/urls.py
from django.urls import path

from . import api_views
from . import views

app_name = 'transacciones'

urlpatterns = [
    path('direct-sales/', views.DirectSalesView.as_view(), name='direct_sales'),
    path('close-day', views.CloseDayView.as_view(), name='close_day'),
    path(
        'add-payment/<int:cliente_id>', views.AddPaymentView.as_view(),
        name='add_payment'
    ),
    path(
        'add-credit/<int:cliente_id>', views.AddCreditView.as_view(),
        name='add_credit'
    ),
    path(
        'edit-credit/<int:pk>/<int:cliente_id>', views.EditCreditView.as_view(),
        name='edit_credit'
    ),
    path(
        'edit-payment/<int:pk>/<int:cliente_id>', views.EditPaymentView.as_view(),
        name='edit_payment'
    ),
    path(
        'edit-transaction/<int:pk>/', views.EditTransactionView.as_view(),
        name='edit_transaction'
    ),
    path(
        'delete-transaction/<int:pk>/', views.delete_transaction,
        name='delete_transaction'
    ),
    path(
        'detalle/<int:cliente_id>',
        views.ListTransactionsView.as_view(),
        name='transacciones_list'
    ),
    path(
        'api/transacciones/<int:cliente_id>',
        api_views.ListarTransaccionesAPIView.as_view(),
        name='listar_transacciones_api'
    ),
    path(
        '',
        views.ListAllTransactionsView.as_view(),
        name='full_transacciones_list'
    ),
    path(
        'api/transacciones/',
        api_views.ListarAllTransaccionesAPIView.as_view(),
        name='listar_all_transacciones_api'
    ),
    path(
        'remember-payment/<int:cliente_id>',
        views.recordar_deuda,
        name='remember_payment'
    ),
    path(
        'cierres',
        views.ListAllCierresView.as_view(),
        name='full_cierres_list'
    ),
    path(
        'api/cierres/',
        api_views.ListarAllCierresAPIView.as_view(),
        name='listar_all_cierres_api'
    ),
]

templates/base.html
{% load static waffle_tags crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% comment %} <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> {% endcomment %}
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <link rel="icon" type="image/x-icon" href="{% static 'img/credicol_logo.png' %}" />
    <script src="{% static 'app/js/app.js' %}"></script>
    <link rel="manifest" href="{% static 'app/manifest.json' %}"/>
    {% block css %}{% endblock css %}

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        {% include "sidebar.html" %}
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                {% include "navbar.html" %}
                {% block content %}
                {% endblock %}
            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; CredicolApp 2024</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Deseas cerrar sesión?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Selecciona "Salir" si deseas cerrar la sesión actual.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                    <a class="btn btn-primary" href="{% url 'user_logout' 'credicol' %}">Salir</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js'%}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js'%}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js'%}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js'%}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js'%}"></script>
    <script src="https://unpkg.com/sweetalert2@7.8.2/dist/sweetalert2.all.js"
        integrity="sha384-TXx4nFk9yfqhYyuOr5TSNDLkwYpxvszQRKWzlWSQopwFpZsUPq/z1wQtH61CW6ex" 
        crossorigin="anonymous">
    </script>
    <script>

        ocultarEnMovil()

        function ocultarEnMovil() {

            if (!window.matchMedia("(max-width: 768px)").matches) {
                $("body").toggleClass("sidebar-toggled");
                $(".sidebar").toggleClass("toggled");
                if ($(".sidebar").hasClass("toggled")) {
                    $('.sidebar .collapse').collapse('hide');
                };
            }
        }

        verificarMembresia()

        function verificarMembresia() {
            var fechaActual = new Date();
            var mes = fechaActual.getMonth() + 1;
            var dia = fechaActual.getDate();
            var fechaActualFormateada = mes + "/" + dia;

            var fechaMembresia = parsearFecha("{{ request.user.company_profile.fin_fecha_membresia }}");
            var diferenciaTiempo = fechaMembresia - fechaActual;
            var diasRestantes = Math.ceil(diferenciaTiempo / (1000 * 60 * 60 * 24));
            var fechaActualMembresia = obtenerFechaActual();
            var membresiaRecordada = localStorage.getItem("membresia");
            var membresiaCaducada = localStorage.getItem("membresia-caducada");

            if (diasRestantes<1 && membresiaCaducada != fechaActualFormateada) {
                const envioMensajes = "{{ request.user.company_profile.envio_mensajes }}"

                const total_membresia = "{{ request.user.company_profile.total_membresia }}"
                const formattedTotalMembresia = parseInt(total_membresia, 10).toLocaleString();
                swal({
                    title: '¡Membresía Caducada!',
                    html: `
                    <p>Tu membresia de CrediCol a caducado, comunicate con un administrador.</p>
                    <div>
                        <br> 
                        <h3><strong>Total a pagar $${formattedTotalMembresia}</strong></h3>
                        <hr>
                        <table>
                            <tr>
                                <td>Consignación o transferencia Bancolombia a la cuenta de ahorros 446-000-16382</td>
                                <td><img style="width:150px;" src="{% static 'img/bancolombia.png' %}" alt="Bancolombia"></td>
                            </tr>
                        </table>
                        <hr>
                        <table>
                            <tr>
                                <td>Numero Whatsapp para envio de comprobantes, recuerde adjuntar a la foto el nombre de su empresa</td>
                                <td><img style="width:150px;" src="{% static 'img/whatsapp.jpg' %}" alt="Bancolombia"></td>
                            </tr>
                        </table>
                    </div>
                `,
                    type: 'warning',
                    showCancelButton: false,
                    showConfirmButton: false,
                    confirmButtonColor: '#4B3FD1',
                    cancelButtonColor: '#7466FF',
                    confirmButtonText: 'Continuar Asi',
                    cancelButtonText: 'Ver Planes',
                    allowOutsideClick: false,
                    width: '600px'
                }).then((result) => {
                    if (result.dismiss == 'cancel') {
                        showPlanes()
                    }
        
                    else if (result.dismiss !== 'cancel') {
                        localStorage.setItem("membresia-caducada", fechaActualFormateada);
                        alert("Recuerda, se deshabilitara el envio de mensaje y recordatorios automaticos a tus clientes y demas funciones especiales.")
                    }
                });
            }
            
            if (diasRestantes <= 3 && diasRestantes >= 0 && fechaActualMembresia !== membresiaRecordada) {
                const total_membresia = "{{ request.user.company_profile.total_membresia }}"
                const formattedTotalMembresia = parseInt(total_membresia, 10).toLocaleString();
                swal({
                    title: '¡Membresía a punto de caducar!',
                    html: `
                    <p>Quedan <strong>${diasRestantes} días</strong> para que su membresía caduque con CrediCol.</p>
                    <div>
                        <br> 
                        <h3><strong>Total a pagar $${formattedTotalMembresia}</strong></h3>
                        <hr>
                        <table>
                            <tr>
                                <td>Consignación o transferencia Bancolombia a la cuenta de ahorros 446-000-16382</td>
                                <td><img style="width:150px;" src="{% static 'img/bancolombia.png' %}" alt="Bancolombia"></td>
                            </tr>
                        </table>
                        <hr>
                        <table>
                            <tr>
                                <td>Numero Whatsapp para envio de comprobantes, recuerde adjuntar a la foto el nombre de su empresa</td>
                                <td><img style="width:150px;" src="{% static 'img/whatsapp.jpg' %}" alt="Bancolombia"></td>
                            </tr>
                        </table>
                    </div>
                `,
                    type: 'info',
                    showCancelButton: false,
                    showConfirmButton: true,
                    confirmButtonColor: '#4B3FD1',
                    cancelButtonColor: '#7466FF',
                    confirmButtonText: 'Aceptar',
                    cancelButtonText: 'Ver Planes',
                    allowOutsideClick: false,
                    width: '600px'
                }).then((result) => {
                    if (result.dismiss == 'cancel') {
                        showPlanes()
                    }
        
                    else if (result.dismiss !== 'cancel') {
                        localStorage.setItem("membresia", fechaActualMembresia);
                    }
                });
            }
        }

        function obtenerFechaActual() {
            var fecha = new Date();
            var dia = fecha.getDate();
            var mes = fecha.getMonth() + 1;
            var año = fecha.getFullYear();
            return año + "-" + mes + "-" + dia;
        }

        function parsearFecha(dateString) {
            const months = {
                'January': 0, 'February': 1, 'March': 2, 'April': 3, 'May': 4, 'June': 5,
                'July': 6, 'August': 7, 'September': 8, 'October': 9, 'November': 10, 'December': 11
            };
        
            let mainParts = dateString.split(', ');
            if (mainParts.length < 3) {
                throw new Error('Invalid date format');
            }
        
            let datePart = mainParts.slice(0, 2).join(', ');
            let timePart = mainParts[2];
        
            console.log(`datePart: ${datePart}, timePart: ${timePart}`);
        
            let [monthDay, year] = datePart.split(', ');
            let [month, day] = monthDay.split(' ');
            day = parseInt(day, 10);
            year = parseInt(year, 10);
        
            console.log(`month: ${month}, day: ${day}, year: ${year}`);
            if (!month || !day || isNaN(year)) {
                throw new Error('Invalid date format');
            }
        
            let [time, period] = timePart.split(' ');
            let [hours, minutes] = time.split(':').map(Number);
            if (isNaN(hours) || isNaN(minutes) || !period) {
                throw new Error('Invalid time format');
            }
        
            console.log(`time: ${time}, period: ${period}, hours: ${hours}, minutes: ${minutes}`);
        
            if (period.toLowerCase() === 'p.m.' && hours !== 12) {
                hours += 12;
            } else if (period.toLowerCase() === 'a.m.' && hours === 12) {
                hours = 0;
            }
        
                const date = new Date(year, months[month], day, hours, minutes);
        
            return date;
        }

        function showPlanes(){
            alert("Consulta Administrador.")
        }
        

    </script>
    {% block js %}
    {% endblock %}
</body>
</html>

templates/sidebar.html
{% load static waffle_tags crispy_forms_tags %}

{% block css %}
    <style>

        ::-webkit-scrollbar {
            width: 7px;
        }

        ::-webkit-scrollbar-track {
            background-color: #FFFFF;
        }

        ::-webkit-scrollbar-thumb {
            background-color: gray;
            border-radius: 1px;
        }

        @media only screen and (max-width: 768px) {
            .elemento-ocultable {
                display: none;
            }

        }

        .ancho-personalizado {
            width: 600px;
        }

        .nav-link.active{
            background-color: #4D1CAF;
            color: white !important;
            border-radius: 10px;
            opacity: 90%;
            margin-left: 5px;
            margin-right: 15px;
        }

        .nav-link.active * {
            color: white;
        }

    </style>
{% endblock css %}
<ul class="navbar-nav bg-gradient-primary sidebar toggled sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'initial_view' %}">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-map-marker-alt fa-1x cc-color-visa"></i>
        </div>
        <div class="sidebar-brand-text mx-3">{{ request.user.company_profile.name }}</div>
    </a>

    {% switch 'see-all' %}
    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    {% comment %} <li class="nav-item active">
        <a class="nav-link" href="index.html">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li> {% endcomment %}

    <!-- Divider -->
    {% comment %} <hr class="sidebar-divider"> {% endcomment %}

    <!-- Heading -->
    {% comment %} <div class="sidebar-heading">
        Interface
    </div> {% endcomment %}

    {% comment %} <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Components</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Components:</h6>
                <a class="collapse-item" href="buttons.html">Buttons</a>
                <a class="collapse-item" href="cards.html">Cards</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Utilities</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Utilities:</h6>
                <a class="collapse-item" href="utilities-color.html">Colors</a>
                <a class="collapse-item" href="utilities-border.html">Borders</a>
                <a class="collapse-item" href="utilities-animation.html">Animations</a>
                <a class="collapse-item" href="utilities-other.html">Other</a>
            </div>
        </div>
    </li> {% endcomment %}

    <!-- Divider -->
    <hr class="sidebar-divider">
    {% endswitch %}
    <br>
    <!-- Heading -->
    <div class="sidebar-heading">
        Acciones
    </div>

    {% switch 'see-all ' %}
    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
            aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Screens:</h6>
                <a class="collapse-item" href="login.html">Login</a>
                <a class="collapse-item" href="register.html">Register</a>
                <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="{% url 'transacciones:direct_sales' %}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Vender</span></a>
    </li>


    {% endswitch %}

    <li class="nav-item">
        <a class="nav-link" href="{% url 'initial_view' %}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Inicio</span></a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'clientes:clientes_list' %}">
            <i class="fas fa-fw fa-user"></i>
            <span>Clientes</span></a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'gastos:full_gastos_list' %}">
            <i class="fas fa-money-bill-wave"></i>
            <span>Gastos</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'transacciones:full_cierres_list' %}">
            <i class="fas fa-cash-register"></i>
            <span>Cierres de Caja</span>
        </a>
    </li>
    

    <li class="nav-item">
        <a class="nav-link" href="{% url 'transacciones:full_transacciones_list' %}">
            <i class="fas fa-exchange-alt"></i>
            <span>Transacciones</span></a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'productos:productos_list' %}">
            <i class="fas fa-fw fa-shopping-cart"></i>
            <span>Productos</span>
        </a>
    </li>

    <br>
    <hr class="sidebar-divider d-none d-md-block">

    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

    {% switch 'see-all' %}

    <!-- Nav Item - Tables -->
   <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-table"></i>
            <span>Tables</span></a>z
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

    <!-- Sidebar Message -->
    <div class="sidebar-card d-none d-lg-flex">
        <img class="sidebar-card-illustration mb-2" src="{% static 'img/undraw_rocket.svg' %}" alt="...">
        <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
        <a class="btn btn-success btn-sm" href="{% static 'https://startbootstrap.com/theme/sb-admin-pro' %}">Upgrade to Pro!</a>
    </div>

    {% endswitch %}

    <form id="delete-form" method="POST">
        {% csrf_token %}
    </form>
    <div id="form-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="form-title"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="form-title"></h5>
                    <button class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="form" method="POST">
                        Cargando...
                    </form>
                </div>
                <div class="modal-footer">
                    <button id="form-button" class="btn btn-primary" type="submit" form="form"></button>
                </div>
            </div>
        </div>
    </div>

</ul>