ROM/urls.py
from django.views.generic import RedirectView
from common.views import LoginUsuario
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from common.views import InitialView, user_logout, RegisterView

urlpatterns = [
    path('credicol-register/', RegisterView.as_view(), name='register'),
    path('admin/', admin.site.urls),
    path('dashboard/', InitialView.as_view(), name='initial_view'),
    path('', RedirectView.as_view(url='/login/')),
    path('login/', LoginUsuario.as_view(), name='login'),
    path('logout/<str:origin>', user_logout, name='user_logout'),
    path('transacciones/', include('transacciones.urls')),
    path('common/', include('common.urls')),
    path('clientes/', include('clientes.urls')),
    path('productos/', include('productos.urls')),
    path('gastos/', include('gastos.urls')),
    path('stv/', include('stv.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/urls.py
from django.urls import path

from . import views, api_views

app_name = 'productos'
urlpatterns = [
    path('', views.ListProductosView.as_view(), name='productos_list'),
    path(
        'api/productos/<str:producto_id>',
        api_views.ListarProductosAPIView.as_view(),
        name='listar_productos_api'
    ),
    # path('cliente/<int:id>', views.ClienteDetailView.as_view(), name='profile'),
    path('add-new', views.AddProductoView.as_view(), name='add_new_producto'),
    path('editar-producto/<int:pk>', views.EditarProductoView.as_view(), name='editar_producto'),
    path('detalle/<int:pk>', views.DetailProductoView.as_view(), name='detalle_producto'),
    # path('editar-cliente/<int:pk>', views.ClienteEditView.as_view(), name='edit_cliente'),
]

productos/models.py
from django.db import models

from django.contrib.auth.models import User


class Producto(models.Model):

    UNIDAD_CHOICES = [
        ('kilo', 'KG'),
        ('libra', 'LB'),
        ('gramos', 'GRM'),
        ('galon', 'GL'),
        ('litro', 'LT'),
        ('cuarto litro', '1/4 LT'),
        ('ml', 'ML'),
        ('unidad', 'UND'),
        ('metros', 'MT'),
        ('centimetro', 'CM'),
    ]

    nombre = models.CharField(max_length=100, unique=True)
    descripcion = models.TextField()
    precio = models.IntegerField(default=0)
    iva = models.FloatField(default=0)
    costo_flete = models.IntegerField(default=0)
    porcentaje_ganancia = models.FloatField(default=0)
    precio_venta = models.IntegerField(default=0)

    compania = models.ForeignKey(
        'companies.CompanyProfile', on_delete=models.CASCADE
    )
    activo = models.BooleanField(default=True)
    creado_por = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True
    )
    stock = models.IntegerField(blank=True, default=0)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

productos/forms.py
from django import forms

from . import models as m


class AddNewProducto(forms.ModelForm):

    class Meta:
        model = m.Producto
        fields = [
            'nombre',
            'precio',
            'iva',
            'costo_flete',
            'porcentaje_ganancia',
            'stock',
            'descripcion',
            'precio_venta'
        ]

        widgets = {
            'descripcion': forms.Textarea(attrs={'style': 'height:100px;'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nombre'].label = ''
        self.fields['precio'].label = ''
        self.fields['stock'].label = ''
        self.fields['descripcion'].label = ''
        self.fields['iva'].label = ''
        self.fields['costo_flete'].label = ''
        self.fields['porcentaje_ganancia'].label = ''
        self.fields['precio_venta'].label = ''

        for field_name, field in self.fields.items():
            field.required = True

    def save(self, user, commit=True):
        producto = super().save(commit=False)
        producto.creado_por = user

        if commit:
            producto.save()

        return producto

    def clean_nombre(self):
        nombre = self.cleaned_data.get('nombre')
        if m.Producto.objects.filter(nombre=nombre).exclude(id=self.instance.id).exists():
            raise forms.ValidationError('Ya existe este nombre de producto')
        return nombre

productos/views.py
from django.views import generic
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django.urls import reverse
from django.http.response import JsonResponse

from . import models as m
from . import forms as f


class ListProductosView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.TemplateView
):

    template_name = 'productos/productos_list.html'
    permission_required = 'transacciones.can_see_cliente_transacciones'


class AddProductoView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.FormView
):
    model = m.Producto
    form_class = f.AddNewProducto
    template_name = 'productos/components/form_add_producto.html'
    permission_required = 'transacciones.can_see_cliente_transacciones'

    def post(self, request, *args, **kwargs):
        modified_post_data = request.POST.copy()
        for field, value in modified_post_data.items():
            modified_post_data[field] = value.replace('.', '')
            if not value:
                modified_post_data[field] = 0

        form = self.get_form_class()(data=modified_post_data)

        if form.is_valid():
            return self.form_valid(form)
        else:
            print(form.errors)
            return self.form_invalid(form)

    def form_valid(self, form):
        product = form.instance.nombre
        compania = self.request.user.company_profile
        form.instance.compania = compania
        form.save(self.request.user)

        return JsonResponse(
            {
                'ok': True, 'product': product, 'label': 'Registrado'
            }
        )


class EditarProductoView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView
):
    model = m.Producto
    form_class = f.AddNewProducto
    template_name = 'productos/components/form_editar_producto.html'
    permission_required = 'transacciones.can_see_cliente_transacciones'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        modified_post_data = request.POST.copy()
        for field, value in modified_post_data.items():
            modified_post_data[field] = value.replace('.', '')
            if not value:
                modified_post_data[field] = 0

        form = self.get_form_class()(data=modified_post_data, instance=self.object)

        if form.is_valid():
            return self.form_valid(form)
        else:
            print(form.errors)
            return self.form_invalid(form)

    def form_valid(self, form):
        product = form.instance.nombre
        compania = self.request.user.company_profile
        form.instance.compania = compania
        form.save(self.request.user)

        return JsonResponse(
            {
                'ok': True, 'product': product, 'label': 'Actualizado'
            }
        )


class DetailProductoView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView
):
    model = m.Producto
    template_name = 'productos/components/detalle_producto.html'
    permission_required = 'transacciones.can_see_cliente_transacciones'

productos/templates/productos/components/detalle_producto.html
{% load crispy_forms_tags %}

{% block css %}
<style>
    body {
        background-color: #f8f9fa;
    }
    .container {
        background-color: #ffffff;
        padding: 30px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        margin-top: 50px;
    }
    .form-group label {
        font-weight: bold;
        color: #495057;
    }
    .form-group input, .form-group textarea, .form-group select {
        border-radius: 4px;
        border: 1px solid #ced4da;
    }
    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        transition: background-color 0.3s, border-color 0.3s;
    }
    .btn-primary:hover {
        background-color: #0056b3;
        border-color: #0056b3;
    }
    .icon-label {
        margin-right: 5px;
        color: #007bff;
    }
    .icon-label-money {
        margin-right: 5px;
        color: #2EC44B;
    }
    .custom-bg {
        background-color: #d4edda;
        border-radius: 5px;
    }
</style>
{% endblock css %}

{% block content %}
<html lang="en">
<head>
    <title>Crear Producto</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.nombre.id_for_label }}"><i class="fas fa-tag icon-label"></i> Nombre del Producto </label>
            <input type="text" class="form-control" name="nombre" id="id_nombre" value="{{ object.nombre|title }}" disabled/>
        </div>
        <div class="row">
            <div class="col col-md-6">
                <div class="form-group">
                    <label for="{{ form.precio.id_for_label }}"><i class="fas fa-dollar-sign icon-label-money"></i> Precio Sin IVA</label>
                    <input type="text" class="form-control" name="precio" id="id_precio" value="{{ object.precio|title }}" disabled/>
                </div>
            </div>
            <div class="col col-md-6">
                <div class="form-group">
                    <label for="{{ form.iva.id_for_label }}"><i class="fas fa-percentage icon-label-money"></i> IVA</label>
                    <input type="text" class="form-control" name="iva" id="id_iva" value="{{ object.iva }} %" disabled/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col col-md-6">
                <div class="form-group">
                    <label for="{{ form.costo_flete.id_for_label }}"><i class="fas fa-truck icon-label-money"></i> Costo Flete</label>
                    <input type="text" class="form-control" name="costo_flete" id="id_costo_flete" value="{{ object.costo_flete }}" disabled/>
                </div>
            </div>
            <div class="col col-md-6">
                <div class="form-group">
                    <label for="{{ form.porcentaje_ganancia.id_for_label }}"><i class="fas fa-percentage icon-label-money"></i> Ganancia</label>
                    <input type="text" class="form-control" name="porcentaje_ganancia" id="id_porcentaje_ganancia" value="{{ object.porcentaje_ganancia }} %" disabled/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col col-md-6">
                <div class="form-group">
                    <label for="{{ form.stock.id_for_label }}"><i class="fas fa-cubes icon-label"></i> Cantidad</label>
                    <input type="text" class="form-control" name="precio_venta" id="id_precio_venta" value="{{ object.stock }}" disabled/>
                </div>
            </div>
            <div class="col col-md-6">
                <div class="form-group custom-bg">
                    <label class="text-green border" for="{{ form.precio_venta.id_for_label }}" style="color: #28a745;">
                        <i class="fas fa-dollar-sign icon-label" style="color: #28a745;"></i> Precio De Venta
                    </label>
                    <input type="text" class="form-control" name="precio_venta" id="id_precio_venta" value="{{ object.precio_venta }}" disabled/>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="{{ form.descripcion.id_for_label }}"><i class="fas fa-comment icon-label"></i> Descripción</label>
            <input type="text" class="form-control" name="precio_venta" id="id_precio_venta" value="{{ object.descripcion }}" disabled/>
        </div>
    </form>
</body>
</html>
{% endblock content %}

productos/templates/productos/components/form_add_producto.html
{% load crispy_forms_tags %}

{% block css %}
<style>
    body {
        background-color: #f8f9fa;
    }
    .container {
        background-color: #ffffff;
        padding: 30px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        margin-top: 50px;
    }
    .form-group label {
        font-weight: bold;
        color: #495057;
    }
    .form-group input, .form-group textarea, .form-group select {
        border-radius: 4px;
        border: 1px solid #ced4da;
    }
    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        transition: background-color 0.3s, border-color 0.3s;
    }
    .btn-primary:hover {
        background-color: #0056b3;
        border-color: #0056b3;
    }
    .icon-label {
        margin-right: 5px;
        color: #007bff;
    }

    .icon-label-money {
        margin-right: 5px;
        color: #2EC44B;
    }

    .custom-bg {
        background-color: #d4edda;
        border-radius: 5px;
    }
</style>
{% endblock css %}

{% block content %}
<html lang="en">
<head>
    <title>Crear Producto</title>
</head>
<body>
    <form method="post" >
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.nombre.id_for_label }}"><i class="fas fa-tag icon-label"></i> Nombre del Producto </label>
            {{ form.nombre|as_crispy_field }}
        </div>
        <div class="row">
            <div class="col col-md-6">
                <div class="form-group">
                    <label for="{{ form.precio.id_for_label }}"><i class="fas fa-dollar-sign icon-label-money"></i> Precio Sin IVA</label>
                    <input type="text" class="form-control" name="precio" id="id_precio" value="0" />
                </div>
            </div>
            <div class="col col-md-6">
                <div class="form-group">
                    <label for="{{ form.iva.id_for_label }}"><i class="fas fa-percentage icon-label-money"></i> IVA</label>
                    <input type="text" class="form-control" name="iva" id="id_iva" placeholder="0 %" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col col-md-6">
                <div class="form-group">
                    <label for="{{ form.costo_flete.id_for_label }}"><i class="fas fa-truck icon-label-money"></i> Costo Flete</label>
                    <input type="text" class="form-control" name="costo_flete" id="id_costo_flete" value="0" />
                </div>
            </div>
            <div class="col col-md-6">
                <div class="form-group">
                    <label for="{{ form.porcentaje_ganancia.id_for_label }}"><i class="fas fa-percentage icon-label-money"></i> Ganancia</label>
                    <input type="text" class="form-control" name="porcentaje_ganancia" id="id_porcentaje_ganancia" placeholder="0 %" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col col-md-6">
                <label for="{{ form.stock.id_for_label }}"><i class="fas fa-cubes icon-label"></i> Cantidad</label>
                {{ form.stock|as_crispy_field }}
            </div>
            <div class="col  col-md-6">
                <div class="form-group" style="background-color: #d4edda; padding: 0px; border-radius: 5px;">
                    <label class="text-green border" for="{{ form.precio_venta.id_for_label }}" style="color: #28a745;">
                        <i class="fas fa-dollar-sign icon-label" style="color: #28a745;"></i> Precio De Venta
                    </label>
                    <input type="text" class="form-control" name="precio_venta" id="id_precio_venta" value="0" />
                </div>
            </div>
        </div>           
        <div class="form-group">
            <label for="{{ form.descripcion.id_for_label }}"><i class="fas fa-comment icon-label"></i> Descripción</label>
            {{ form.descripcion|as_crispy_field }}
        </div>
    </form>

</body>
</html>
{% endblock content %}

{% block js %}
<script>
    alert("ya")
</script>
{% endblock js %}

productos/templates/productos/components/form_editar_producto.html
{% load crispy_forms_tags %}

{% block css %}
<style>
    body {
        background-color: #f8f9fa;
    }
    .container {
        background-color: #ffffff;
        padding: 30px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        margin-top: 50px;
    }
    .form-group label {
        font-weight: bold;
        color: #495057;
    }
    .form-group input, .form-group textarea, .form-group select {
        border-radius: 4px;
        border: 1px solid #ced4da;
    }
    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        transition: background-color 0.3s, border-color 0.3s;
    }
    .btn-primary:hover {
        background-color: #0056b3;
        border-color: #0056b3;
    }
    .icon-label {
        margin-right: 5px;
        color: #007bff;
    }

    .icon-label-money {
        margin-right: 5px;
        color: #2EC44B;
    }

    .custom-bg {
        background-color: #d4edda;
        border-radius: 5px;
    }
</style>
{% endblock css %}

{% block content %}
<html lang="en">
<head>
    <title>Crear Producto</title>
</head>
<body>
    <form method="post" >
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.nombre.id_for_label }}"><i class="fas fa-tag icon-label"></i> Nombre del Producto </label>
            {{ form.nombre|as_crispy_field }}
        </div>
        <div class="row">
            <div class="col col-md-6">
                <div class="form-group">
                    <label for="{{ form.precio.id_for_label }}"><i class="fas fa-dollar-sign icon-label-money"></i> Precio Sin IVA</label>
                    <input type="text" class="form-control" name="precio" id="id_precio" value="{{ form.precio.value }}" />
                </div>
            </div>
            <div class="col col-md-6">
                <div class="form-group">
                    <label for="{{ form.iva.id_for_label }}"><i class="fas fa-percentage icon-label-money"></i> IVA</label>
                    <input type="text" class="form-control" name="iva" id="id_iva" placeholder="{{ form.iva.value }}" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col col-md-6">
                <div class="form-group">
                    <label for="{{ form.costo_flete.id_for_label }}"><i class="fas fa-truck icon-label-money"></i> Costo Flete</label>
                    <input type="text" class="form-control" name="costo_flete" id="id_costo_flete" value="{{ form.costo_flete.value }}" />
                </div>
            </div>
            <div class="col col-md-6">
                <div class="form-group">
                    <label for="{{ form.porcentaje_ganancia.id_for_label }}"><i class="fas fa-percentage icon-label-money"></i> Ganancia</label>
                    <input type="text" class="form-control" name="porcentaje_ganancia" id="id_porcentaje_ganancia" placeholder="{{ form.porcentaje_ganancia.value }}" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col col-md-6">
                <label for="{{ form.stock.id_for_label }}"><i class="fas fa-cubes icon-label"></i> Cantidad</label>
                {{ form.stock|as_crispy_field }}
            </div>
            <div class="col  col-md-6">
                <div class="form-group" style="background-color: #d4edda; padding: 0px; border-radius: 5px;">
                    <label class="text-green border" for="{{ form.precio_venta.id_for_label }}" style="color: #28a745;">
                        <i class="fas fa-dollar-sign icon-label" style="color: #28a745;"></i> Precio De Venta
                    </label>
                    <input type="text" class="form-control" name="precio_venta" id="id_precio_venta" value="{{ form.precio_venta.value }}" />
                </div>
            </div>
        </div>           
        <div class="form-group">
            <label for="{{ form.descripcion.id_for_label }}"><i class="fas fa-comment icon-label"></i> Descripción</label>
            {{ form.descripcion|as_crispy_field }}
        </div>
    </form>

</body>
</html>
{% endblock content %}

{% block js %}
<script>
    alert("ya")
</script>
{% endblock js %}